Repository epitech-mirroring/RTX, pull requests merged in 2024-05, with the labels that each got.

#43 🪟 Basic window
  .gitignore
  Makefile
  include/Application.hpp
  include/Camera.hpp
  include/Object.hpp
  include/Transform.hpp
  shaders/raytracing.frag
  shaders/screen.vert
  src/Application.cpp
  src/Camera.cpp
  src/Transform.cpp
  src/main.cpp
  src/objects/Object.cpp
  src/primitives/Cube.cpp
Labels: enhancement

#48 :sparkles: Generating ppm and add more options
  include/Application.hpp
  include/Raytracer.hpp
  scenes/simple.json
  shaders/raytracing.comp
  src/Application.cpp
  src/Scene.cpp
  src/main.cpp
Labels: enhancement

#50 🪞 Specular Reflections
  include/Application.hpp
  include/Object.hpp
  scenes/simple.json
  scenes/smoothness.json
  shaders/raytracing.comp
  src/Application.cpp
  src/main.cpp
Labels: enhancement, lights

#49 🗺️ Planes
  Makefile
  include/primitives/Plane.hpp
  include/primitives/Properties/PlaneProperties.hpp
  scenes/tests/scenePlane.json
  src/main.cpp
  src/primitives/Plane.cpp
  src/primitives/Properties/PlaneProperties.cpp
Labels: enhancement, primitives

#53 🥽 Transparency and Refractions
  include/Material.hpp
  include/Object.hpp
  scenes/transparency.json
  shaders/raytracing.comp
  src/Application.cpp
  src/main.cpp
  src/objects/Material.cpp
  tests/testsMaterial.cpp
Labels: enhancement, lights

#55 :link: Link obj parser to scene parser
  include/SceneParser.hpp
  scenes/tests/sceneObj.json
  src/SceneParser.cpp
  src/main.cpp
Labels: enhancement

#56 🍩 add torus
  Makefile
  include/primitives/Properties/TorusProperties.hpp
  include/primitives/Torus.hpp
  scenes/tests/sceneTorus.json
  src/main.cpp
  src/primitives/Properties/TorusProperties.cpp
  src/primitives/Torus.cpp
Labels: enhancement, primitives

#59 :movie_camera: Add scene in a scene
  include/SceneParser.hpp
  scenes/tests/sceneScene.json
  src/SceneParser.cpp
  src/primitives/Torus.cpp
Labels: enhancement

#60 🏁 Procedural checker pattern
  include/Material.hpp
  include/Object.hpp
  scenes/simple.json
  shaders/raytracing.comp
  src/Application.cpp
  src/objects/Material.cpp
Labels: materials

#61 🎨 Textures
  Makefile
  assets/glowstone.png
  assets/grass.png
  include/Application.hpp
  include/Object.hpp
  include/Texture.hpp
  scenes/simple.json
  shaders/raytracing.comp
  src/Application.cpp
  src/objects/Texture.cpp
  src/primitives/Cone.cpp
  src/primitives/Cube.cpp
  src/primitives/Cylinder.cpp
  src/primitives/Plane.cpp
  src/primitives/Rectangle.cpp
  src/primitives/Sphere.cpp
Labels: materials
